/*
 * Header example
 */
package com.example;

/**
 * MethodLengthのコード例です。
 * 
 * @author example
 * @since 1.0.0
 */
public class MethodLengthExample {

    /**
     * MethodLengthのコード例です（NG）。
     */
    public void example() {
        System.out.println(1);
        System.out.println(2);
        System.out.println(3);
        System.out.println(4);
        System.out.println(5);
        System.out.println(6);
        System.out.println(7);
        System.out.println(8);
        System.out.println(9);
        System.out.println(10);
        System.out.println(11);
        System.out.println(12);
        System.out.println(13);
        System.out.println(14);
        System.out.println(15);
        System.out.println(16);
        System.out.println(17);
        System.out.println(18);
        System.out.println(19);
        System.out.println(20);
        System.out.println(21);
        System.out.println(22);
        System.out.println(23);
        System.out.println(24);
        System.out.println(25);
        System.out.println(26);
        System.out.println(27);
        System.out.println(28);
        System.out.println(29);
        System.out.println(30);
        System.out.println(31);
        System.out.println(32);
        System.out.println(33);
        System.out.println(34);
        System.out.println(35);
        System.out.println(36);
        System.out.println(37);
        System.out.println(38);
        System.out.println(39);
        System.out.println(40);
        System.out.println(41);
        System.out.println(42);
        System.out.println(43);
        System.out.println(44);
        System.out.println(45);
        System.out.println(46);
        System.out.println(47);
        System.out.println(48);
        System.out.println(49);
        System.out.println(50);
        System.out.println(51);
        System.out.println(52);
        System.out.println(53);
        System.out.println(54);
        System.out.println(55);
        System.out.println(56);
        System.out.println(57);
        System.out.println(58);
        System.out.println(59);
        System.out.println(60);
        System.out.println(61);
        System.out.println(62);
        System.out.println(63);
        System.out.println(64);
        System.out.println(65);
        System.out.println(66);
        System.out.println(67);
        System.out.println(68);
        System.out.println(69);
        System.out.println(70);
        System.out.println(71);
        System.out.println(72);
        System.out.println(73);
        System.out.println(74);
        System.out.println(75);
        System.out.println(76);
        System.out.println(77);
        System.out.println(78);
        System.out.println(79);
        System.out.println(80);
        System.out.println(81);
        System.out.println(82);
        System.out.println(83);
        System.out.println(84);
        System.out.println(85);
        System.out.println(86);
        System.out.println(87);
        System.out.println(88);
        System.out.println(89);
        System.out.println(90);
        System.out.println(91);
        System.out.println(92);
        System.out.println(93);
        System.out.println(94);
        System.out.println(95);
        System.out.println(96);
        System.out.println(97);
        System.out.println(98);
        System.out.println(99);
        System.out.println(100);
        System.out.println(101);
        System.out.println(102);
        System.out.println(103);
        System.out.println(104);
        System.out.println(105);
        System.out.println(106);
        System.out.println(107);
        System.out.println(108);
        System.out.println(109);
        System.out.println(110);
        System.out.println(111);
        System.out.println(112);
        System.out.println(113);
        System.out.println(114);
        System.out.println(115);
        System.out.println(116);
        System.out.println(117);
        System.out.println(118);
        System.out.println(119);
        System.out.println(120);
        System.out.println(121);
        System.out.println(122);
        System.out.println(123);
        System.out.println(124);
        System.out.println(125);
        System.out.println(126);
        System.out.println(127);
        System.out.println(128);
        System.out.println(129);
        System.out.println(130);
        System.out.println(131);
        System.out.println(132);
        System.out.println(133);
        System.out.println(134);
        System.out.println(135);
        System.out.println(136);
        System.out.println(137);
        System.out.println(138);
        System.out.println(139);
        System.out.println(140);
        System.out.println(141);
        System.out.println(142);
        System.out.println(143);
        System.out.println(144);
        System.out.println(145);
        System.out.println(146);
        System.out.println(147);
        System.out.println(148);
        System.out.println(149);
    }
}
