
@startuml
ブラウザ -> Webアプリ: リクエスト
Webアプリ -> DB: データ登録
ブラウザ <-- Webアプリ: レスポンス
テーブルをキューとして使ったメッセージング -> DB: データ監視
テーブルをキューとして使ったメッセージング -> テーブルをキューとして使ったメッセージング: 処理
DB <- テーブルをキューとして使ったメッセージング: 更新
@enduml
