
@startuml
Browser -> "Web App": Request
"Web App" -> DB: Data registration
Browser <-- "Web App": Response
"Messaging Using Tables as Queues" -> DB: Data monitoring
"Messaging Using Tables as Queues" -> "Messaging Using Tables as Queues": Processing
DB <- "Messaging Using Tables as Queues": Update
@enduml
