FIND_PROJECT_IN_PERIOD =
SELECT
    PROJECT_ID,
    PROJECT_NAME,
    PROJECT_TYPE,
    PROJECT_CLASS,
    PROJECT_START_DATE,
    PROJECT_END_DATE,
    ORGANIZATION_ID,
    CLIENT_ID,
    PROJECT_MANAGER,
    PROJECT_LEADER,
    NOTE,
    SALES,
    VERSION_NO
FROM
    PROJECT
WHERE
    PROJECT_START_DATE <= ?
    AND PROJECT_END_DATE >= ?
ORDER BY
    PROJECT_START_DATE, PROJECT_END_DATE, PROJECT_NAME