FIND_PROJECT_IN_PERIOD =
SELECT
    P.PROJECT_ID projectId,
    P.PROJECT_NAME,
    P.PROJECT_TYPE,
    P.PROJECT_CLASS,
    P.PROJECT_START_DATE,
    P.PROJECT_END_DATE,
    P.ORGANIZATION_ID,
    P.CLIENT_ID,
    P.PROJECT_MANAGER,
    P.PROJECT_LEADER,
    P.NOTE,
    P.SALES,
    P.VERSION
FROM
    PROJECT P
    , BUSINESS_DATE B
WHERE
    B.SEGMENT_ID = '00'
    AND P.PROJECT_START_DATE <= to_date(B.BIZ_DATE, 'YYYYMMDD')
    AND P.PROJECT_END_DATE >= to_date(B.BIZ_DATE, 'YYYYMMDD')
ORDER BY
    P.PROJECT_START_DATE, P.PROJECT_END_DATE, P.PROJECT_NAME