pipeline {
  agent any
  triggers {
    pollSCM('*/1 * * * *')
  }
  tools {
    maven 'mvn3'
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '3'))
  }
  environment {
    SONAR_HOST_URL = 'http://10.0.1.133/sonarqube'
    // 以下は開発環境の接続情報である。
    // 全ての開発者が知っても差し支えない情報であるため、全ての開発者が参照できるファイル(本ファイル)に記載している。
    DEMO_HOST = '10.0.1.100'
    DEMO_PORT = '22'
    DEMO_USERNAME = 'centos'
    DEMO_PASSWORD = 'pass789-'
    //ビルドする際のカレントディレクトリ
    PROJECT_CURRENT_DIR = 'サンプルアプリケーション/ソースコード/proman-project/'
  }
  stages {
    stage('mvn install') {
      steps {
        echo 'mvn install'
        dir(PROJECT_CURRENT_DIR) {
          sh 'mvn clean -s ci/settings.xml -Dmaven.repo.local=${WORKSPACE}/repository'
          sh 'mvn -P gsp clean generate-resources -pl proman-common -s ci/settings.xml -Dmaven.repo.local=${WORKSPACE}/repository'
          sh 'mvn -P demo,!development install -s ci/settings.xml -Dmaven.repo.local=${WORKSPACE}/repository'
        }
       }
       post {
        success { rocketSend message: 'mvn install', emoji: ':blush:' }
        failure { rocketSend message: 'mvn install', emoji: ':sob:' }
      }
    }

    stage('checkstyle and spotbugs') {
      steps {
        echo 'checkstyle and spotbugs'
        dir(PROJECT_CURRENT_DIR) {
          catchError {
              sh 'mvn checkstyle:checkstyle spotbugs:check -pl proman-common -s ci/settings.xml -Dmaven.repo.local=${WORKSPACE}/repository'
              sh 'mvn checkstyle:checkstyle spotbugs:check -pl proman-web -s ci/settings.xml -Dmaven.repo.local=${WORKSPACE}/repository'
          }
          sh 'mvn site -s ci/settings.xml'
          archiveArtifacts allowEmptyArchive: true, artifacts: 'proman-common/target/site/**'
          archiveArtifacts allowEmptyArchive: true, artifacts: 'proman-web/target/site/**'
        }
      }
      post {
        success { rocketSend message: 'proman-common checkstyle and spotbugs', emoji: ':blush:' }
        failure { rocketSend message: 'proman-common checkstyle and spotbugs', emoji: ':sob:' }
      }
    }

    stage('report field') {
      steps {
        echo 'report field'
        dir(PROJECT_CURRENT_DIR) {
          catchError {
            sh 'mvn -pl proman-web -s ci/settings.xml exec:java -Dexec.classpathScope="test" -Dexec.mainClass=nablarch.tool.inspection.reportField.CLI -Dexec.args=@reportField-web.config -Dmaven.repo.local=${WORKSPACE}/repository'
          }
          archiveArtifacts 'proman-web/target/web-reportField.csv'
        }
      }
      post {
        success { rocketSend message: 'checkstyle and spotbugs', emoji: ':blush:' }
        failure { rocketSend message: 'checkstyle and spotbugs', emoji: ':sob:' }
      }
    }

    stage('create executable jar') {
      when {
        allOf {
          branch 'develop'
          expression { return currentBuild.result != 'FAILURE' }
        }
      }
      steps {
        echo 'Create executable jar'
        dir(PROJECT_CURRENT_DIR) {
          sh 'mvn -P demo,!development clean compile -pl proman-web -s ci/settings.xml -Dmaven.repo.local=${WORKSPACE}/repository'
          sh 'mvn -P demo,!development waitt:jar -pl proman-web -s ci/settings.xml -Dmaven.repo.local=${WORKSPACE}/repository'
        }
      }
      post {
        success { rocketSend message: 'create executable jar', emoji: ':blush:' }
        failure { rocketSend message: 'create executable jar', emoji: ':sob:' }
      }
    }

    stage('Deploy to demo') {
      when {
        allOf {
          branch 'develop'
          expression { return currentBuild.result != 'FAILURE' }
        }
      }
      steps {
        echo 'Create app resources'
        dir(PROJECT_CURRENT_DIR) {
          sh 'rm -rf app-proman-web'
          sh 'mkdir -p app-proman-web'
          sh 'mkdir -p app-proman-web/web'
          sh 'cp -r proman-web/ci/deploy-to-demo/* app-proman-web/'
          sh 'cp $(find proman-web/target/ -name *standalone.jar) app-proman-web/web'
          sh 'cp -r proman-web/src/main/webapp/ app-proman-web/web/webapp/'
          sh 'mvn clean'
          sh 'mkdir -p app-proman-web/web/project'
          sh 'cp -r pom.xml app-proman-web/web/project/'
          sh 'cp -r ci app-proman-web/web/project/'
          sh 'cp -r proman-web app-proman-web/web/project/'
          sh 'cp -r proman-common app-proman-web/web/project/'
          echo 'Send app to demo'
          sh 'sshpass -p ${DEMO_PASSWORD} ssh -p ${DEMO_PORT} -oStrictHostKeyChecking=no ${DEMO_USERNAME}@${DEMO_HOST} "rm -rf app-proman-web"'
          sh 'sshpass -p ${DEMO_PASSWORD} scp -P ${DEMO_PORT} -oStrictHostKeyChecking=no -r app-proman-web/ ${DEMO_USERNAME}@${DEMO_HOST}:~/'
          sh 'sshpass -p ${DEMO_PASSWORD} ssh -p ${DEMO_PORT} -oStrictHostKeyChecking=no ${DEMO_USERNAME}@${DEMO_HOST} "ls -lR app-proman-web"'
          echo 'Start app'
          sh 'sshpass -p ${DEMO_PASSWORD} ssh -p ${DEMO_PORT} -oStrictHostKeyChecking=no ${DEMO_USERNAME}@${DEMO_HOST} "cd app-proman-web && sh up.sh"'
          archiveArtifacts 'app-proman-web/**'
        }
      }
      post {
        success { rocketSend message: 'Deploy to demo', emoji: ':blush:' }
        failure { rocketSend message: 'Deploy to demo', emoji: ':sob:' }
      }
    }
  }
}