-------------------------------------------------------------------------------
-- プロジェクトIDによる検索
-------------------------------------------------------------------------------
FIND_PROJECT_WITH_ORGANIZATION_BY_ID =
SELECT
  P.PROJECT_ID AS PROJECT_ID
  , P.PROJECT_NAME AS PROJECT_NAME
  , P.PROJECT_TYPE AS PROJECT_TYPE
  , P.PROJECT_CLASS AS PROJECT_CLASS
  , P.PROJECT_START_DATE AS PROJECT_START_DATE
  , P.PROJECT_END_DATE AS PROJECT_END_DATE
  , P.ORGANIZATION_ID AS ORGANIZATION_ID
  , P.CLIENT_ID AS CLIENT_ID
  , P.PROJECT_MANAGER AS PROJECT_MANAGER
  , P.PROJECT_LEADER AS PROJECT_LEADER
  , P.NOTE AS NOTE
  , P.SALES AS SALES
  , P.VERSION AS VERSION
  , O.ORGANIZATION_ID AS ORGANIZATION_ID
  , O.ORGANIZATION_NAME AS ORGANIZATION_NAME
  , UO.ORGANIZATION_ID AS DIVISION_ID
  , UO.ORGANIZATION_NAME AS DIVISION_NAME
FROM
  PROJECT P
  , ORGANIZATION O
  , ORGANIZATION UO
WHERE
    1 = 1
  AND P.ORGANIZATION_ID = O.ORGANIZATION_ID
  AND O.UPPER_ORGANIZATION = UO.ORGANIZATION_ID
  AND P.PROJECT_ID = ?
