version: "3"
 
services:
  web:
    build: $PWD/web/ # Specifying the file to build
    image: web # Image name
    container_name: web # Container name
    ports: # Port on the left to access,right side is the port inside the container
      - "80:3333"
    links:
      - postgres
    stdin_open: true
    tty: true
 
  postgres:
    image: postgres:10.4-alpine # Base image file
    container_name: postgres # Container name
    ports: # Port on the left to access,right side is the port inside the container
      - "5432:5432" 
    environment: # Container internal environment variable
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=postgres"